name: Waka Readme

on:
  workflow_dispatch:

  schedule:
    - cron: '00 18,00 * * *'

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    environment: Wakatime
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_TITLE: true
          SECTION_NAME: wakatime
          SHOW_TIME: true
          SHOW_TOTAL: true
          SHOW_MASKED_TIME: false
          LANG_COUNT: 10
          CODE_LANG: go
          TIME_RANGE: all_time
          COMMIT_MESSAGE: Updated waka-readme graph with new metrics
          TARGET_BRANCH: main
          TARGET_PATH: README.md
          COMMITTER_NAME: Bot
          COMMITTER_EMAIL: bot@aldiwildan.me
          AUTHOR_NAME: Aldiwildan77
          AUTHOR_EMAIL: dev@aldiwildan.me
          
